name: Plan
author: Rsl1122
main: com.djrapitops.plan.Plan
version: @version@
api-version: 1.13
softdepend:
  - AAC
  - ASkyBlock
  - AdvancedAchievements
  - AdvancedBan
  - BanManager
  - BentoBox
  - CoreProtect
  - DiscordSRV
  - DKBans
  - Essentials
  - Factions
  - GriefPrevention
  - GriefPreventionPlus
  - Jobs
  - LiteBans
  - LuckPerms
  - mcMMO
  - MinigamesLib
  - nuVotifier
  - PlaceholderAPI
  - ProtocolSupport
  - RedProtect
  - SuperbVote
  - Towny
  - Vault
  - ViaVersion

commands:
  plan:
    usage: /plan help
    description: base command

permissions:
  plan.?:
    description: Help command
    default: true
  plan.inspect.base:
    description: Allows you to check your player data.
    default: true
  plan.inspect.other:
    description: Allows you to check other players' player data.
    default: op
  plan.qinspect.base:
    description: Allows you to check your player data.
    default: op
  plan.qinspect.other:
    description: Allows you to check other players' player data.
  plan.analyze:
    description: Allows you to check analysed data about all players.
    default: op
  plan.qanalyze:
    description: Allows you to check analysed data about all players.
    default: op
  plan.reload:
    description: Allows to reload plugin config
    default: op
  plan.search:
    description: Allows search
    default: op
  plan.info:
    description: Allows to view info
    default: op
  plan.ignore.commanduse:
    description: Commands used by this player are not saved
    default: false
  plan.ignore.afk:
    description: AFK time by this player is ignored
    default: false
  plan.manage:
    description: Manage the database, clear, move, combine.
    default: op
  plan.webmanage:
    description: Manage the webusers, delete, list, check
    default: op

  plan.basic:
    children:
      plan.?: true
      plan.inspect.base: true
      plan.qinspect.base: true
  plan.advanced:
    childer:
      plan.basic: true
      plan.info: true
      plan.qanalyze: true
  plan.staff:
    children:
      plan.search: true
      plan.advanced: true
      plan.analyze: true
      plan.inspect.other: true
      plan.qinspect.other: true
      plan.webmanage: true
      plan.reload: true
  plan.*:
    children:
      plan.manage: true
      plan.staff: true
      apf.notify: true