categories:
  - title: 'New'
    label: 'Feature'
  - title: 'Improvements'
    label: 'enhancement'
  - title: 'Bugfixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Dependencies'
    label: 'dependencies'
template: |
  # _ Change log

  $CHANGES
